export interface Departamento {
  nombre: string;
  municipios: string[];
}

export const DEPARTAMENTOS_SV: Departamento[] = [
  {
    nombre: "Ahuachapán",
    municipios: [
      "Ahuachapán",
      "Apaneca",
      "Atiquizaya",
      "Concepción de Ataco",
      "El Refugio",
      "Guaymango",
      "Jujutla",
      "San Francisco Menéndez",
      "San Lorenzo",
      "San Pedro Puxtla",
      "Tacuba",
      "Turín",
    ],
  },
  {
    nombre: "Santa Ana",
    municipios: [
      "Santa Ana",
      "Candelaria de la Frontera",
      "Chalchuapa",
      "Coatepeque",
      "El Congo",
      "El Porvenir",
      "Masahuat",
      "Metapán",
      "San Antonio Pajonal",
      "San Sebastián Salitrillo",
      "Santa Rosa Guachipilín",
      "Santiago de la Frontera",
      "Texistepeque",
    ],
  },
  {
    nombre: "Sonsonate",
    municipios: [
      "Sonsonate",
      "Acajutla",
      "Armenia",
      "Caluco",
      "Cuisnahuat",
      "Izalco",
      "Juayúa",
      "Nahuizalco",
      "Nahulingo",
      "Salcoatitán",
      "San Antonio del Monte",
      "San Julián",
      "Santa Catarina Masahuat",
      "Santa Isabel Ishuatán",
      "Santo Domingo de Guzmán",
      "Sonzacate",
    ],
  },
  {
    nombre: "Chalatenango",
    municipios: [
      "Chalatenango",
      "Agua Caliente",
      "Arcatao",
      "Azacualpa",
      "Citalá",
      "Comalapa",
      "Concepción Quezaltepeque",
      "Dulce Nombre de María",
      "El Carrizal",
      "El Paraíso",
      "La Laguna",
      "La Palma",
      "La Reina",
      "Las Vueltas",
      "Nombre de Jesús",
      "Nueva Concepción",
      "Nueva Trinidad",
      "Ojos de Agua",
      "Potonico",
      "San Antonio de la Cruz",
      "San Antonio Los Ranchos",
      "San Fernando",
      "San Francisco Lempa",
      "San Francisco Morazán",
      "San Ignacio",
      "San Isidro Labrador",
      "San Luis del Carmen",
      "San Miguel de Mercedes",
      "San Rafael",
      "Santa Rita",
      "Tejutla",
    ],
  },
  {
    nombre: "La Libertad",
    municipios: [
      "Santa Tecla",
      "Antiguo Cuscatlán",
      "Ciudad Arce",
      "Colón",
      "Comasagua",
      "Chiltiupán",
      "Huizúcar",
      "Jayaque",
      "Jicalapa",
      "La Libertad",
      "Magdalena",
      "Nuevo Cuscatlán",
      "San Juan Opico",
      "Quezaltepeque",
      "Sacacoyo",
      "San José Villanueva",
      "San Matías",
      "San Pablo Tacachico",
      "Talnique",
      "Tamanique",
      "Teotepeque",
      "Tepecoyo",
      "Zaragoza",
    ],
  },
  {
    nombre: "San Salvador",
    municipios: [
      "San Salvador",
      "Aguilares",
      "Apopa",
      "Ayutuxtepeque",
      "Cuscatancingo",
      "Ciudad Delgado",
      "El Paisnal",
      "Guazapa",
      "Ilopango",
      "Mejicanos",
      "Nejapa",
      "Panchimalco",
      "Rosario de Mora",
      "San Marcos",
      "San Martín",
      "Santiago Texacuangos",
      "Santo Tomás",
      "Soyapango",
      "Tonacatepeque",
    ],
  },
  {
    nombre: "Cuscatlán",
    municipios: [
      "Cojutepeque",
      "El Carmen",
      "El Rosario",
      "Monte San Juan",
      "Oratorio de Concepción",
      "San Bartolomé Perulapía",
      "San Cristóbal",
      "San José Guayabal",
      "San Pedro Perulapán",
      "San Rafael Cedros",
      "San Ramón",
      "Santa Cruz Analquito",
      "Santa Cruz Michapa",
      "Suchitoto",
      "Tenancingo",
    ],
  },
  {
    nombre: "La Paz",
    municipios: [
      "Zacatecoluca",
      "Cuyultitán",
      "El Rosario",
      "Jerusalén",
      "Mercedes La Ceiba",
      "Olocuilta",
      "Paraíso de Osorio",
      "San Antonio Masahuat",
      "San Emigdio",
      "San Francisco Chinameca",
      "San Juan Nonualco",
      "San Juan Talpa",
      "San Juan Tepezontes",
      "San Luis La Herradura",
      "San Luis Talpa",
      "San Miguel Tepezontes",
      "San Pedro Masahuat",
      "San Pedro Nonualco",
      "San Rafael Obrajuelo",
      "Santa María Ostuma",
      "Santiago Nonualco",
      "Tapalhuaca",
    ],
  },
  {
    nombre: "Cabañas",
    municipios: [
      "Sensuntepeque",
      "Cinquera",
      "Dolores",
      "Guacotecti",
      "Ilobasco",
      "Jutiapa",
      "San Isidro",
      "San Lorenzo",
      "Tejutepeque",
      "Victoria",
    ],
  },
  {
    nombre: "San Vicente",
    municipios: [
      "San Vicente",
      "Apastepeque",
      "Guadalupe",
      "San Cayetano Istepeque",
      "San Esteban Catarina",
      "San Ildefonso",
      "San Lorenzo",
      "San Sebastián",
      "Santa Clara",
      "Santo Domingo",
      "Tepetitán",
      "Verapaz",
    ],
  },
  {
    nombre: "Usulután",
    municipios: [
      "Usulután",
      "Alegría",
      "Berlín",
      "California",
      "Concepción Batres",
      "El Triunfo",
      "Ereguayquín",
      "Estanzuelas",
      "Jiquilisco",
      "Jucuapa",
      "Jucuarán",
      "Mercedes Umaña",
      "Nueva Granada",
      "Ozatlán",
      "Puerto El Triunfo",
      "San Agustín",
      "San Buenaventura",
      "San Dionisio",
      "San Francisco Javier",
      "Santa Elena",
      "Santa María",
      "Santiago de María",
      "Tecapán",
    ],
  },
  {
    nombre: "San Miguel",
    municipios: [
      "San Miguel",
      "Carolina",
      "Chapeltique",
      "Chinameca",
      "Chirilagua",
      "Ciudad Barrios",
      "Comacarán",
      "El Tránsito",
      "Lolotique",
      "Moncagua",
      "Nueva Guadalupe",
      "Nuevo Edén de San Juan",
      "Quelepa",
      "San Antonio",
      "San Gerardo",
      "San Jorge",
      "San Luis de la Reina",
      "San Rafael Oriente",
      "Sesori",
      "Uluazapa",
    ],
  },
  {
    nombre: "Morazán",
    municipios: [
      "San Francisco Gotera",
      "Arambala",
      "Cacaopera",
      "Corinto",
      "Delicias de Concepción",
      "El Divisadero",
      "El Rosario",
      "Gualococti",
      "Guatajiagua",
      "Joateca",
      "Jocoaitique",
      "Jocoro",
      "Lolotiquillo",
      "Meanguera",
      "Osicala",
      "Perquín",
      "San Carlos",
      "San Fernando",
      "San Isidro",
      "San Simón",
      "Sensembra",
      "Sociedad",
      "Torola",
      "Yamabal",
      "Yoloaiquín",
    ],
  },
  {
    nombre: "La Unión",
    municipios: [
      "La Unión",
      "Anamorós",
      "Bolívar",
      "Concepción de Oriente",
      "Conchagua",
      "El Carmen",
      "El Sauce",
      "Intipucá",
      "Lislique",
      "Meanguera del Golfo",
      "Nueva Esparta",
      "Pasaquina",
      "Polorós",
      "San Alejo",
      "San José",
      "Santa Rosa de Lima",
      "Yayantique",
      "Yucuaiquín",
    ],
  },
];

export const getMunicipios = (departamento: string): string[] => {
  const dep = DEPARTAMENTOS_SV.find((d) => d.nombre === departamento);
  return dep ? dep.municipios : [];
};
