import { useMemo } from "react";
import { Platform, StyleSheet } from "react-native";
import { FONTS, useTheme } from "../context/ThemeContext";
import { shadow } from "../utils/shadow";

// Efecto "glass" SOLO en web (en nativo se ignora).
// Se castea como any porque `backdropFilter` es CSS puro (no parte del tipo RN).
const WEB_GLASS = Platform.OS === "web"
  ? ({ backdropFilter: "blur(18px)", WebkitBackdropFilter: "blur(18px)" } as any)
  : ({} as any);

// ══════════════════════════════════════════════════════════════════
//  Paleta del panel admin — theme-aware (claro / oscuro).
//  El modo OSCURO conserva EXACTAMENTE el diseño original (morados
//  profundos). El modo CLARO deriva una variante legible equivalente.
// ══════════════════════════════════════════════════════════════════
export const makeC = (isDark: boolean) => ({
  // Alineado con la paleta global de la app (ThemeContext) para que el admin
  // se sienta parte del mismo producto, manteniendo el morado como identidad.
  bg: isDark ? "#0F0A1E" : "#F6F4FD",
  surface: isDark ? "rgba(26,16,48,0.92)" : "rgba(255,255,255,0.92)",
  surfaceAlt: isDark ? "rgba(36,22,66,0.72)" : "rgba(239,234,251,0.92)",
  surfaceSoft: isDark ? "rgba(26,16,48,0.72)" : "rgba(255,255,255,0.78)",
  accent: "#7C3AED",
  accent70: isDark ? "#A78BFA" : "#6D28D9",
  accent40: "rgba(124,58,237,0.35)",
  accent20: "rgba(124,58,237,0.12)",
  accent10: "rgba(124,58,237,0.08)",
  text: isDark ? "#F5F3FF" : "#241B3D",
  textSub: isDark ? "rgba(245,243,255,0.82)" : "rgba(36,27,61,0.78)",
  textMuted: isDark ? "rgba(245,243,255,0.56)" : "rgba(36,27,61,0.55)",
  border: isDark ? "rgba(124,58,237,0.20)" : "rgba(124,58,237,0.16)",
  borderStrong: isDark ? "rgba(124,58,237,0.32)" : "rgba(124,58,237,0.26)",
  cardBg: isDark ? "rgba(26,16,48,0.68)" : "rgba(255,255,255,0.82)",
  green: isDark ? "rgba(52,211,153,1)" : "#059669",
  greenBg: isDark ? "rgba(52,211,153,0.08)" : "rgba(5,150,105,0.10)",
  yellow: "#f59e0b",
  yellowBg: "rgba(245,158,11,0.12)",
  red: "#ef4444",
  redBg: "rgba(239,68,68,0.10)",
});

export type AdminColors = ReturnType<typeof makeC>;

/**
 * Hook único de tema del panel admin. Devuelve la paleta `C`, los estilos `s`
 * memorizados y `isDark`. Todos los componentes del panel (incl. Badge/Chip/
 * Card a nivel de módulo) lo consumen para reaccionar al tema claro/oscuro.
 */
export function useAdminTheme() {
  const { isDark, toggleTheme } = useTheme();
  const C = useMemo(() => makeC(isDark), [isDark]);
  const s = useMemo(() => makeStyles(C), [C]);
  return { C, s, isDark, toggleTheme };
}

export const makeStyles = (C: AdminColors) => StyleSheet.create({
  root: { flex: 1, backgroundColor: C.bg, paddingTop: 0 },
  topbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 14,
    backgroundColor: C.surfaceSoft,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    ...WEB_GLASS,
    ...shadow({ color: "#05030b", y: 12, blur: 34, opacity: 0.16, elevation: 8 }),
  },
  topbarDesktop: {
    paddingHorizontal: 28,
    paddingTop: 22,
    paddingBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  topbarCompact: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 12,
  },
  topbarLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
    flexWrap: "wrap",
  },
  topbarLeftCompact: {
    gap: 8,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.accent10,
    ...shadow({ color: "#05030b", y: 8, blur: 22, opacity: 0.10, elevation: 3 }),
  },
  brandRowCompact: {
    gap: 6,
    paddingHorizontal: 9,
    paddingVertical: 7,
    borderRadius: 14,
  },
  brandImg: { width: 24, height: 24 },
  brandDivider: { width: 1, height: 18, backgroundColor: C.border },
  brandImgSecondary: { width: 28, height: 28 },
  brand: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: C.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  brandText: { color: C.text, fontSize: 18, fontWeight: "900", fontFamily: FONTS.soraExtraBold },
  topbarTitle: { color: C.text, fontSize: 16, fontWeight: "900", fontFamily: FONTS.soraExtraBold },
  topbarSubtitle: { color: C.textMuted, fontSize: 11, marginTop: 3, fontWeight: "700", fontFamily: FONTS.interMedium },
  topbarRight: { flexDirection: "row", alignItems: "center", gap: 10 },
  topbarRightCompact: {
    gap: 8,
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  iconBtn: {
    width: 42,
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.surfaceAlt,
    ...WEB_GLASS,
    ...shadow({ color: "#05030b", y: 8, blur: 18, opacity: 0.12, elevation: 3 }),
  },
  langTag: {
    position: "absolute",
    bottom: 3,
    right: 3,
    paddingHorizontal: 3,
    borderRadius: 5,
    backgroundColor: C.accent20,
  },
  langTagText: {
    fontSize: 8,
    fontWeight: "800",
    color: C.accent70,
  },
  navBadge: {
    position: "absolute",
    top: 5,
    right: 5,
    backgroundColor: C.accent,
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderWidth: 1,
    borderColor: C.borderStrong,
    minWidth: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  navBadgeText: { color: "#fff", fontSize: 10, fontWeight: "900" },
  main: { flex: 1, flexDirection: "row" },
  mainDesktop: {
    alignItems: "stretch",
  },
  content: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 18,
  },
  contentDesktop: {
    paddingHorizontal: 28,
    paddingTop: 28,
    paddingBottom: 28,
  },
  contentCompact: {
    paddingHorizontal: 12,
    paddingTop: 14,
    paddingBottom: 12,
  },
  contentWithBottomNav: {
    paddingBottom: 110,
  },
  contentInner: {
    flex: 1,
  },
  contentInnerDesktop: {
    flex: 1,
    width: "100%",
    maxWidth: 1480,
    alignSelf: "center",
  },
  drawerOverlay: {
    flex: 1,
    backgroundColor: "rgba(15,10,30,0.70)",
    flexDirection: "row",
  },
  drawerPanel: {
    width: 320,
    maxWidth: "85%",
    height: "100%",
    backgroundColor: C.surfaceSoft,
    borderRightWidth: 1,
    borderRightColor: C.border,
    paddingTop: 18,
    paddingBottom: 16,
    ...WEB_GLASS,
  },
  drawerHeader: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  drawerTitle: { color: C.text, fontSize: 14, fontWeight: "900", fontFamily: FONTS.soraExtraBold },
  drawerSub: { color: C.textMuted, fontSize: 12, marginTop: 2, fontFamily: FONTS.interRegular },
  drawerBackdrop: { flex: 1 },
  sidebarRail: {
    width: 252,
    paddingTop: 18,
    paddingLeft: 14,
    paddingBottom: 110,
    backgroundColor: "transparent",
  },
  sidebarCard: {
    width: 228,
    maxHeight: "100%",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surfaceSoft,
    overflow: "hidden",
    ...WEB_GLASS,
    ...shadow({ color: "#05030b", x: 10, y: 0, blur: 34, opacity: 0.16, elevation: 6 }),
  },
  sidebarCardCollapsed: {
    width: 72,
  },
  sidebarHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  sidebarHeaderCollapsed: {
    paddingHorizontal: 8,
  },
  sidebarBody: {
    paddingHorizontal: 6,
    paddingTop: 10,
    paddingBottom: 14,
  },
  sidebarBurger: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surfaceAlt,
    paddingHorizontal: 10,
    paddingVertical: 9,
    alignSelf: "flex-start",
  },
  sidebarBurgerExpanded: {
    paddingRight: 14,
  },
  sidebarBurgerText: {
    color: C.textSub,
    fontSize: 12,
    fontWeight: "800",
    fontFamily: FONTS.interSemiBold,
  },
  sidebarLogoMini: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(139,92,246,0.14)",
    borderWidth: 1,
    borderColor: "rgba(139,92,246,0.24)",
    alignSelf: "center",
  },
  sidebarTitle: { color: C.text, fontSize: 14, fontWeight: "900", fontFamily: FONTS.soraExtraBold },
  sidebarSub: { color: C.textMuted, fontSize: 12, marginTop: 2, fontFamily: FONTS.interRegular },
  sidebarItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 11,
    marginHorizontal: 8,
    marginTop: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surfaceAlt,
    ...WEB_GLASS,
  },
  sidebarItemCollapsed: {
    justifyContent: "center",
    paddingHorizontal: 0,
    marginHorizontal: 6,
  },
  sidebarItemIconWrap: {
    width: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  sidebarItemActive: {
    backgroundColor: C.accent20,
    borderColor: C.borderStrong,
  },
  sidebarItemText: { color: C.textMuted, fontSize: 13, fontWeight: "700", fontFamily: FONTS.interSemiBold },
  sidebarItemTextActive: { color: C.accent70 },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 18,
  },
  heroPanel: {
    borderRadius: 30,
    padding: 24,
    borderWidth: 1,
    borderColor: C.borderStrong,
    backgroundColor: C.cardBg,
    marginBottom: 18,
    overflow: "hidden",
    ...WEB_GLASS,
    ...shadow({ color: "#05030b", y: 18, blur: 40, opacity: 0.16, elevation: 10 }),
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 14,
    flexWrap: "wrap",
  },
  // Apila el bloque de texto sobre los botones en vez de dejarlos competir
  // por espacio en la misma fila: en `row` + `flexWrap`, el texto ({flex:1})
  // podía terminar comprimido a un ancho mínimo y partirse palabra por
  // palabra. En columna, el texto ocupa todo el ancho y envuelve con normalidad.
  heroTopRowCompact: {
    flexDirection: "column",
    alignItems: "flex-start",
  },
  heroEyebrow: {
    color: C.accent70,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.8,
    textTransform: "uppercase",
    fontFamily: FONTS.interSemiBold,
  },
  heroTitle: {
    color: C.text,
    fontSize: 32,
    fontWeight: "900",
    lineHeight: 38,
    marginTop: 8,
    fontFamily: FONTS.soraExtraBold,
  },
  heroSubtitle: {
    color: C.textSub,
    fontSize: 13,
    lineHeight: 21,
    marginTop: 10,
    maxWidth: 760,
    fontFamily: FONTS.interRegular,
  },
  heroBadgeRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 16 },
  heroBadge: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surfaceAlt,
  },
  heroBadgeText: { color: C.textSub, fontSize: 11, fontWeight: "700", fontFamily: FONTS.interMedium },
  heroActionRow: { flexDirection: "row", gap: 10, flexWrap: "wrap", marginTop: 18 },
  heroMetricsRow: { flexDirection: "row", gap: 12, flexWrap: "wrap", marginTop: 22 },
  heroMetricCard: {
    flex: 1,
    minWidth: 180,
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surfaceAlt,
    ...WEB_GLASS,
  },
  heroMetricValue: { color: C.text, fontSize: 32, fontWeight: "900", marginTop: 10, fontFamily: FONTS.rajdhaniBold },
  heroMetricLabel: { color: C.textSub, fontSize: 13, fontWeight: "700", marginTop: 4, fontFamily: FONTS.interSemiBold },
  heroMetricHint: { color: C.textMuted, fontSize: 12, marginTop: 6, fontFamily: FONTS.interRegular },
  kicker: {
    color: C.accent70,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1.8,
    marginBottom: 4,
    fontFamily: FONTS.interSemiBold,
  },
  pageTitle: { color: C.text, fontSize: 28, fontWeight: "900", lineHeight: 34, fontFamily: FONTS.soraExtraBold },
  textMuted: { color: C.textMuted },
  card: {
    backgroundColor: C.cardBg,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: C.border,
    padding: 18,
    ...WEB_GLASS,
    ...shadow({ color: "#05030b", y: 14, blur: 30, opacity: 0.12, elevation: 5 }),
  },
  cardTitle: { color: C.text, fontSize: 15, fontWeight: "800", fontFamily: FONTS.interSemiBold },
  cardTitleLg: { color: C.text, fontSize: 18, fontWeight: "900", fontFamily: FONTS.soraExtraBold },
  row: { flexDirection: "row", alignItems: "center" },
  grid2: { flexDirection: "row", flexWrap: "wrap", gap: 14 },
  panelSection: { marginTop: 18, marginBottom: 2 },
  sectionPill: {
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.accent10,
    marginBottom: 12,
    ...WEB_GLASS,
  },
  sectionPillText: { color: C.accent70, fontSize: 11, fontWeight: "800", letterSpacing: 1.2, fontFamily: FONTS.interSemiBold },
  chipRow: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" },
  chip: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surfaceAlt,
    ...WEB_GLASS,
  },
  chipActive: {
    backgroundColor: C.accent20,
    borderColor: C.borderStrong,
  },
  chipText: { color: C.textMuted, fontSize: 12, fontWeight: "700", fontFamily: FONTS.interMedium },
  chipTextActive: { color: C.accent70, fontWeight: "800" },
  badge: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: "flex-start",
  },
  badgeText: { fontSize: 10, fontWeight: "800", fontFamily: FONTS.interSemiBold, letterSpacing: 0.4 },
  statCard: {
    flex: 1,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.cardBg,
    padding: 18,
    minHeight: 150,
    // NO "space-between": el ícono, el número y la etiqueta deben quedar
    // juntos arriba (el espaciado real ya lo dan los marginTop de cada
    // Text) — con space-between se estiraban a los extremos de la tarjeta,
    // dejando huecos enormes en el medio.
    ...WEB_GLASS,
    ...shadow({ color: "#05030b", y: 14, blur: 30, opacity: 0.12, elevation: 6 }),
  },
  statCardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  statIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.surfaceAlt,
    borderWidth: 1,
    borderColor: C.border,
    ...WEB_GLASS,
  },
  statValue: { color: C.text, fontSize: 36, fontWeight: "900", marginTop: 12, fontFamily: FONTS.rajdhaniBold },
  statLabel: { color: C.textSub, fontSize: 14, fontWeight: "800", marginTop: 6, fontFamily: FONTS.interSemiBold },
  statMeta: { color: C.textMuted, fontSize: 12, marginTop: 8, lineHeight: 18, fontFamily: FONTS.interRegular },
  metricTile: {
    flex: 1,
    minHeight: 136,
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surfaceAlt,
    ...WEB_GLASS,
  },
  metricTileLabel: { color: C.text, fontSize: 14, fontWeight: "800", marginTop: 12, fontFamily: FONTS.interSemiBold },
  metricTileValue: { fontSize: 32, fontWeight: "900", marginTop: 16, fontFamily: FONTS.rajdhaniBold, color: C.text },
  metricTileSub: { color: C.textMuted, fontSize: 12, marginTop: 6, lineHeight: 18, fontFamily: FONTS.interRegular },
  searchWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: C.surfaceAlt,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 12,
    ...WEB_GLASS,
  },
  searchInput: { flex: 1, color: C.text, fontSize: 13, fontFamily: FONTS.interRegular },
  listItem: {
    flexDirection: "row",
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 18,
    backgroundColor: C.surfaceSoft,
    alignItems: "center",
    ...WEB_GLASS,
    ...shadow({ color: "#05030b", y: 10, blur: 22, opacity: 0.10, elevation: 3 }),
  },
  listItemStack: {
    flexDirection: "column",
    gap: 10,
  },
  listItemAsideCompact: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: C.accent20,
    borderWidth: 1,
    borderColor: C.borderStrong,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  avatarText: { color: C.accent70, fontWeight: "900", fontSize: 16, fontFamily: FONTS.soraExtraBold },
  itemTitle: { color: C.text, fontSize: 13, fontWeight: "800", fontFamily: FONTS.interSemiBold },
  itemSub: { color: C.textMuted, fontSize: 12, marginTop: 2, lineHeight: 18, fontFamily: FONTS.interRegular },
  notifItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 18,
    backgroundColor: C.surfaceSoft,
    ...WEB_GLASS,
    ...shadow({ color: "#05030b", y: 10, blur: 22, opacity: 0.10, elevation: 3 }),
  },
  notifItemUnread: {
    borderLeftWidth: 3,
    borderLeftColor: C.accent,
    backgroundColor: C.accent10,
    paddingLeft: 12,
  },
  logItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 18,
    backgroundColor: C.surfaceSoft,
    ...WEB_GLASS,
    ...shadow({ color: "#05030b", y: 10, blur: 22, opacity: 0.10, elevation: 3 }),
  },
  permItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 18,
    backgroundColor: C.surfaceAlt,
    ...WEB_GLASS,
    ...shadow({ color: "#05030b", y: 10, blur: 20, opacity: 0.08, elevation: 3 }),
  },
  permItemActive: {
    backgroundColor: C.accent10,
    borderColor: C.borderStrong,
  },
  togglePill: {
    width: 44,
    height: 24,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surfaceAlt,
    justifyContent: "center",
    paddingHorizontal: 3,
    ...WEB_GLASS,
  },
  togglePillOn: { backgroundColor: C.accent20, borderColor: C.borderStrong },
  toggleDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "rgba(255,255,255,0.35)",
    alignSelf: "flex-start",
  },
  toggleDotOn: { alignSelf: "flex-end", backgroundColor: C.accent70 },
  progressWrap: {
    height: 6,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 6,
    overflow: "hidden",
  },
  progressBar: { height: 6, backgroundColor: C.accent70, borderRadius: 6 },
  btnPrimary: {
    backgroundColor: C.accent,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
    ...shadow({ color: "#05030b", y: 12, blur: 26, opacity: 0.18, elevation: 5 }),
  },
  btnPrimaryText: { color: "#fff", fontWeight: "800", fontSize: 14, fontFamily: FONTS.interSemiBold, letterSpacing: 0.2 },
  btnOutline: {
    borderWidth: 1,
    borderColor: C.borderStrong,
    borderRadius: 16,
    paddingVertical: 11,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.surfaceAlt,
    ...WEB_GLASS,
  },
  btnOutlineText: { color: C.accent70, fontWeight: "700", fontSize: 13, fontFamily: FONTS.interSemiBold },
  actionTile: {
    flex: 1,
    minWidth: 190,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surfaceAlt,
    padding: 16,
    gap: 10,
    ...WEB_GLASS,
  },
  actionTileTitle: { color: C.text, fontSize: 14, fontWeight: "800", fontFamily: FONTS.interSemiBold },
  actionTileText: { color: C.textMuted, fontSize: 12, lineHeight: 18, fontFamily: FONTS.interRegular },
  btnSm: { paddingVertical: 7, paddingHorizontal: 12, borderRadius: 8 },
  btnSmText: { fontSize: 12 },
  inputLabel: {
    color: C.textMuted,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 8,
    fontFamily: FONTS.interMedium,
  },
  input: {
    backgroundColor: C.surfaceAlt,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: C.text,
    fontSize: 13,
    fontFamily: FONTS.interRegular,
    ...WEB_GLASS,
  },
  bottomNav: {
    flexDirection: "row",
    backgroundColor: C.surfaceSoft,
    borderWidth: 1,
    borderColor: C.border,
    paddingBottom: 12,
    paddingTop: 10,
    paddingHorizontal: 10,
    justifyContent: "space-around",
    borderRadius: 24,
    ...WEB_GLASS,
    ...shadow({ color: "#05030b", y: 16, blur: 34, opacity: 0.22, elevation: 10 }),
  },
  bottomNavWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 18,
    paddingHorizontal: 12,
  },
  bottomNavWrapDesktop: {
    alignItems: "center",
    left: 0,
    right: 0,
  },
  bottomNavDesktop: {
    width: "100%",
    maxWidth: 620,
  },
  bottomNavItem: {
    flex: 1,
    alignItems: "center",
    gap: 5,
    paddingVertical: 7,
    borderRadius: 14,
    minWidth: 48,
  },
  bottomNavItemActive: {
    backgroundColor: C.accent10,
    borderWidth: 1,
    borderColor: C.borderStrong,
  },
  bottomNavLabel: { color: C.textMuted, fontSize: 9, fontWeight: "700", fontFamily: FONTS.interSemiBold },
  bottomNavLabelActive: { color: C.accent70 },
  bottomNavBadge: {
    position: "absolute",
    top: -6,
    right: -8,
    minWidth: 18,
    height: 18,
    borderRadius: 999,
    paddingHorizontal: 4,
    backgroundColor: C.red,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    alignItems: "center",
    justifyContent: "center",
  },
  bottomNavBadgeText: { color: "#fff", fontSize: 9, fontWeight: "900", fontFamily: FONTS.interSemiBold },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15,10,30,0.72)",
    justifyContent: "flex-end",
  },
  modal: {
    backgroundColor: C.surfaceSoft,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderWidth: 1,
    borderColor: C.border,
    padding: 24,
    maxHeight: "92%",
    ...WEB_GLASS,
    ...shadow({ color: "#05030b", y: -18, blur: 44, opacity: 0.22, elevation: 12 }),
  },
  modalCompact: {
    maxWidth: "100%",
    maxHeight: "96%",
    padding: 18,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
  },
  formRowCompact: {
    flexDirection: "column",
    gap: 12,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  modalTitle: { color: C.text, fontSize: 16, fontWeight: "900", fontFamily: FONTS.soraExtraBold },
});
